[package]
name = "cpp_demangle_js"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[dependencies]
cpp_demangle = "0.2.0"
